### PR TITLE
Fix foot servo limit rotation on walk and turn

### PR DESCRIPTION
**Pull request by RobertoDebarba**
On walk or turn actions one foot rotation reach the servo physical limit.  
The problem was the wrong rotation direction.

### CODE REVIEW

**Comment by cparrapa** [comment]
Hi @RobertoDebarba 

Thanks for your contribution, did you check that probably fitted the legs on backwards?

We had no problem with these 2 functions.

Checked the library and they do not move to the max possible position, +-60 degrees is the amount of movement from zero

Where did you connected the servos?

Best

**Comment by RobertoDebarba** [comment]
Hi.

I guess is not possible to build the leg backwards. I attached some photos. Curiosaly the problem only happened with one leg. Home() command also works pretty well.  
  
I'm using a nodeMCU with esp8266 for this project (a little chalenge), so the pin set does not fit with the build instructions. I gonna attach the code and some photos.

IMG_20191010_210924
IMG_20191010_210919
```
#include <Otto9.h>
Otto9 Otto;  //This is Otto!

#define PIN_LEFTLEG 4 //D2
#define PIN_RIGHTLEG 0 //D3
#define PIN_LEFTFOOT 16 //D0
#define PIN_RIGHTFOOT 5 //D1
#define PIN_NOISE_SENSOR 12
#define PIN_BUZZER 13
#define PIN_USTRIGGER 14
#define PIN_USECHO 15

void setup() {
Otto.init(PIN_LEFTLEG,PIN_RIGHTLEG,PIN_LEFTFOOT,PIN_RIGHTFOOT,true,PIN_NOISE_SENSOR,PIN_BUZZER,PIN_USTRIGGER,PIN_USECHO); //Set the servo pins
	Otto.sing(S_connection);
	Otto.home(); //Works well here
	delay(50);
}

void loop() {
	Otto.walk(10,1000,1); //Problem happens here
	
}
```

**Comment by cparrapa** [comment]
Hi Roberto

So if with the nodeMCU has different pins then better try to match the hardware to our libraries so that is fully compatible. What do you think @jarsoftelectrical ?

It is pretty cool that you are using ESP, hope to see some cool ioT applications here, what are your ideas? many people wanted to make Otto with it but there is none that has documented well it could be a great chance for you to participate in the #OttoREMIXchallenge https://www.ottodiy.com/blog/challenge

**Comment by RobertoDebarba** [comment]
I am building a educational visual programming language with Otto.
It provides a more attractive solution to teach programming.

I choose the ESP8266 instead arduino because of the lower price and WIFI capabilities. There are no need of cables to flash the programam. With just one click the firmware is updated over the air via internet.

image

**Comment by cparrapa** [comment]
Hi Roberto
This is amazing, we can work in this parallel way of programming Otto.
We are also working in this blockly environment for Otto https://t.me/joinchat/AFZv-EqrYqyaghg3wXggRQ
is there a way we can combine both repos?

Thanks

**Comment by cparrapa** [comment]
Hi @RobertoDebarba 
We made a new blockly and already have ESP32 but can we add your commands better there? https://www.ottodiy.com/#blockly-and-app

**Comment by RobertoDebarba** [comment]
@cparrapa I gonna look the new project near in the future. Unfortunately I don't have time now.

I'm closing this PR because don't make sense here ant more.

**Comment by cparrapa** [comment]
Hi @RobertoDebarba thanks hope to see you back soon

**Pull request closed without merging**
