### PR TITLE
add missing pinMode to OttoMatrix

### PR DESCRIPTION
**Pull request by mcapinha**
I lost my matrix display after having updated my Otto to the App V9 sketch.
Comparing my old library with this, I found it missing the setup of the load pin.

### CODE REVIEW

**Comment by cparrapa** [comment]
Hi Manual
Thanks for checking that , @jarsoftelectrical was this lost somehow on the transition or is intentional?

**Comment by cparrapa** [comment]
Hi @mcapinha 

There is some conflict with the files not able to merge

Thanks

**Comment by mcapinha** [comment]
The missing pinMode has been fixed by https://github.com/OttoDIY/Libraries/commit/79e8d1c53dc5e570b3a1b25f0428b2237e72e016, which reverted the ESP32 changes.
So my fix isn't needed anymore, I'm closing this.

**Comment by cparrapa** [comment]
right thanks for noticing and let us know!

**Pull request closed without merging**
