### PR TITLE
Revert "Including ESP32 support"

### PR DESCRIPTION
**Pull request by cparrapa**
Reverts OttoDIY/Libraries#2

Hi @mishafarms we see some missing lines with this changes did you tested that works also for arduino nano?

In this case then we will have your contribution as part of the main repo 
https://github.com/OttoDIY/DIY

Thanks!

### CODE REVIEW

**Comment by mishafarms** [comment]
I am sorry about the issue of missing lines. I will fix things up in the new repository. I would really like to have one set of libraries for all CPUs.

**Comment by jarsoftelectrical** [comment]
This is great idea for the future, one universal library, at the moment we are unable to test this as neither myself nor Camilo have an ESP32, once we can confirm everything is OK for all devices then we can merge together, I feel it is better to keep them separate at this moment. This doesn't take away from you the great work you have done and it is appreciated and is a valuable asset, please continue to work with us on your libraries and we will merge them together hopefully soon. 

⁣Sent from TypeApp ​

**Comment by mishafarms** [comment]
I understand.

I have fixed the missing line and I will test later today (I do not have a matrix on a Nano yet). When I do I will request a pull into the ESP repository.

**Comment by jarsoftelectrical** [comment]
Brilliant, many thanks

⁣Sent from TypeApp ​

**Pull request merged**
